jobs:
  build_test_deploy:
    working_directory: ~/DVT-BOOKS
    docker:
      - image: circleci/node:12.9.1-browsers
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package-lock.json" }}
            - v1-dependencies-
      - run:
          name: Install dependencies
          command: npm install
      - save_cache:
          key: v1-dependencies-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
      - run:
          name: Linting
          command: npm run lint
      - run:
          name: Test
          command: npm run test --  --source-map=false --no-watch --no-progress --browsers=ChromeHeadlessCI
      - run:
          name: Build
          command: ./node_modules/@angular/cli/bin/ng build --prod

workflows:
  version: 2
  build_test_deploy:
    jobs:
      - build_test_deploy
